server:
  port: 8080

spring:
  application:
    name: kings

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update

    open-in-view: false

    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

file:
  storage:
    path: ${FILE_STORAGE_PATH:./files}

web:
  cors:
    allowed-origins:
      - https://thekingscompany.co.kr
      - https://admin.thekingscompany.co.kr
      - https://www.thekingscompany.co.kr
      - https://www.admin.thekingscompany.co.kr

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret: ${JWT_SECRET:change-this-secret-key-change-this-secret-key}
  access-token-expiration-seconds: ${JWT_ACCESS_TOKEN_EXPIRATION_SECONDS:3600}
